version: '3.3'

services:
  api:
    build: .
    ports:
      - 8080:8080
    links:
      - postgres
    depends_on:
      - postgres
    environment:
      IS_DEBUG: 0
      SERVER_ADDR: :8080
      DB_CONNSTRING: postgresql://postgres@postgres/chainstack?sslmode=disable

  postgres:
    image: postgres
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  data:
    driver: local
